name: Pre-Merge Checks

on:
  pull_request:
    branches:
      - main
  workflow_run:
    workflows: ["Pylint", "gitleaks", "codeql"]
    types:
      - completed

jobs:
  build:
    name: pre-merge-check
    runs-on: ubuntu-latest
    strategy:
  #    fail-fast: true
      matrix:
        language: ['python']

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      run: |
        docker build -t new:v1 .
        docker image tag new:v1 mansi1811/new:v1

    - name: Set up Trivy
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/master/contrib/install.sh | sh -s -- -b /usr/local/bin
        trivy -v

    - name: Scan Docker Image for Vulnerabilities with Trivy
      run: |
        trivy image  --severity=HIGH,CRITICAL new:v1
      # continue-on-error: false
      # if: ${{ success() }}

    - name: Check vulnerability
      run: |
        trivy_output=$(trivy image --severity HIGH --no-progress new:v1)
        python - <<EOF
        import sys

        if 'Total: 0' in "$trivy_output":
            print('No vulnerability found')
        else:
            print('Vulnerability found')
            sys.exit(1)  # Terminate the workflow
        EOF
           # python - <<EOF
           # import sys

           #  if 'Total: 0' in "$trivy_output":
           #      print('No vulnerability found')
           #  else:
           #      print('Vulnerability found')
           #  sys.exit(1)  # Terminate the workflow
           #  EOF
        # if echo "$trivy_output" | grep -q 'Total: 0'; then
        #   echo 'No vulnerability found'
        # else
        #   echo 'Vulnerability found'
        #   exit 1
        # fi
        
    - name: Push Docker Image
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push mansi1811/new:v1
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      shell: bash
